// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbgUbufBeiodprjdJzwDYaZy2aPbes4n8',
    appId: '1:991883682804:web:9cced466b21ec13a248fa1',
    messagingSenderId: '991883682804',
    projectId: 'sn-global-4c941',
    authDomain: 'sn-global-4c941.firebaseapp.com',
    storageBucket: 'sn-global-4c941.appspot.com',
    measurementId: 'G-P0G2GC109C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxriCAwBw0kCFbENDlu90vgrmjHYczyVU',
    appId: '1:991883682804:android:964978c459e34f72248fa1',
    messagingSenderId: '991883682804',
    projectId: 'sn-global-4c941',
    storageBucket: 'sn-global-4c941.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzHBg85SG7d4SMwRuAHQp-aA4zkXxVru0',
    appId: '1:991883682804:ios:bbfe0f367fc70a78248fa1',
    messagingSenderId: '991883682804',
    projectId: 'sn-global-4c941',
    storageBucket: 'sn-global-4c941.appspot.com',
    androidClientId: '991883682804-88lgagh4sf2hcnk9rdkg6cq38egcgglb.apps.googleusercontent.com',
    iosClientId: '991883682804-g0p90ejpumbkkvphc40ngkrmc0glmm87.apps.googleusercontent.com',
    iosBundleId: 'com.example.snglobal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzHBg85SG7d4SMwRuAHQp-aA4zkXxVru0',
    appId: '1:991883682804:ios:bbfe0f367fc70a78248fa1',
    messagingSenderId: '991883682804',
    projectId: 'sn-global-4c941',
    storageBucket: 'sn-global-4c941.appspot.com',
    androidClientId: '991883682804-88lgagh4sf2hcnk9rdkg6cq38egcgglb.apps.googleusercontent.com',
    iosClientId: '991883682804-g0p90ejpumbkkvphc40ngkrmc0glmm87.apps.googleusercontent.com',
    iosBundleId: 'com.example.snglobal',
  );
}
